### ISSUE TITLE
Github Actions support

### ISSUE THREAD

**Issue by muznyo** [ImranR98/Obtainium#102]
Some repositories use Github Actions for releasing prerelease packages instead of prerelease section in releases page. It would be great to support it!

**Comment by ImranR98** [comment]
Could you provide an example repo

**Comment by LuanVSO** [comment]
[skyline emulator](https://github.com/skyline-emu/skyline/actions?query=branch%3Aftx1) is another example, they only provide packages through github actions.

**Comment by BHydden** [comment]
If you don't want to use their fdroid or play release, you also need actions for https://github.com/TrianguloY/UrlChecker

**Comment by schklom** [comment]
I vote that the repositories make releases part of their GitHub Actions.

That's how I do it, and it works well.
Note that I don't develop apps, I simply build them from source or download them from non-GitHub places, and release them.
Example 1: build and release an apk https://github.com/schklom/Gadgetbridge-osm with the GitHub Actions [sync](https://github.com/schklom/Mirror-workflows/blob/main/.github/workflows/Gadgetbridge%20repo%20sync.yml) and [build+release](https://github.com/schklom/Mirror-workflows/blob/main/.github/workflows/Gadgetbridge-osm%20build%2Brelease%20master.yml)
Example 2: download and release an apk https://github.com/schklom/CubeACR-apk with the GitHub Action [download + release](https://github.com/schklom/Mirror-workflows/blob/main/.github/workflows/Download%2BRelease%20CubeACR.yml)

A possible GitHub Action release
```yaml
      - name: Release apk
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ env.version }}"
          body: "app-main-debug.apk is the Gadgetbridge file with osmand-experiments patches"
          files: |
             ./app/build/outputs/apk/main/debug/app-main-debug.apk
          repository: "schklom/Gadgetbridge-osm"
          token: ${{ secrets.PAT_GITHUB_ACTION }}
```
